### ISSUE TITLE
Propick not displaying ore concentration

### ISSUE THREAD

**Issue by MrChakotay** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#134]
### Version modpack Used

Default

### Environment

Singleplayer and Multiplayer

### New Worlds

Yes

### Expected Behavior

Expected to output information about the concentration and type of ore when right clicking on a known location with ore

### Actual Behavior

The Propick only displays "Nothing of interest found" or no text at all.

### Steps to Reproduce

Find a know location with ore and use the Propick.

### Additional Information

java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.speeedcraft.tfgmod.gregtech.items.tools.behaviors.PropickBehavior$ProspectResult cannot be cast to net.dries007.tfc.objects.items.metal.ItemProspectorPick$ProspectResult
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_361]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_361]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]

**Comment by SpeeeDCraft** [comment]
We are aware of this problem, we are fixing it at the moment, but we thank you anyway.
